version: '3'
rpc:
    listen: 'tcp://127.0.0.1:6001'
server:
    command: 'php src/backend/App.php'
    relay: pipes  
http:
    address: '127.0.0.1:8000'
    middleware:
        - gzip
        - headers
    pool:
        num_workers: 1
        supervisor:
            max_worker_memory: 100
    headers:
        response:
            Content-Security-Policy: "default-src 'self'; script-src 'self'; object-src 'none'; frame-ancestors 'none'; base-uri 'self'; form-action 'self';"
            X-Content-Type-Options: "nosniff"
            X-Frame-Options: "DENY"
            Referrer-Policy: "same-origin"
            Permissions-Policy: "camera=(), microphone=(), geolocation=()"
            Cross-Origin-Resource-Policy: "same-origin"
            Cross-Origin-Embedder-Policy: "require-corp"
            Cross-Origin-Opener-Policy: "same-origin"
        cors:
            allowed_origin: "http://localhost:5173"
            allowed_headers: "Content-Type, Authorization, X-Requested-With, X-CSRF-TOKEN"
            allowed_methods: "GET,POST"
            allow_credentials: true
            max_age: 600
service:
    refresh_sessions_cleaner:
        command: "php src/backend/Services/RefreshSessionsCleaner.php"
        process_num: 1
        timeout_stop_sec: 300
    master_key_rotator:
        command: "php src/backend/Services/MasterKeyRotator.php"
        process_num: 1
        timeout_stop_sec: 1200
jobs:
    pool:
        num_workers: 2
        max_worker_memory: 100
    consume: {  }
kv:
    local:
        driver: memory
        config:
            interval: 60
metrics:
    address: '127.0.0.1:2112'
